name: deploy-auth-container

on:
  push:
    branches:
      - master
    paths:
      - "packages/auth/**"

defaults:
  run:
    working-directory: packages/auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          aws-region: ap-south-1

      - name: Syncing dist with S3 bucket
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/auth/latest

      - name: Invalidate index.html
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DIST_ID }} --paths "/auth/latest/remoteEntry.js"
